{
 "title": "Pizza Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{source=\"jwt-pizza-service-dev\"} | json"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "active_users_ratio{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "Active Users"
    }
   ]
  },
  {
   "title": "Purchases and Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(pizza_sold_total{source=\"jwt-pizza-service-dev\"}[30s])",
     "legendFormat": "Pizza purchases"
    },
    {
     "expr": "rate(pizza_creation_failures_total{source=\"jwt-pizza-service-dev\"}[30s])",
     "legendFormat": "Purchase Failures"
    }
   ]
  },
  {
   "title": "HTTP requests by method/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(http_requests_by_method_total{source=\"jwt-pizza-service-dev\"}[30s])",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "rate(http_requests_total{source=\"jwt-pizza-service-dev\"}[30s])",
     "legendFormat": "Total Requests"
    }
   ]
  },
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "pizza_creation_latency_ms_milliseconds{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "Pizza latency"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "endpoint_latency_ms_milliseconds{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "CPU and Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage_percent{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "memory_usage_percent{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "rate(auth_attempts_success_total{source=\"jwt-pizza-service-dev\"}[30s])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(auth_attempts_failure_total{source=\"jwt-pizza-service-dev\"}[30s])",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "rate(pizza_revenue_USD_total{source=\"jwt-pizza-service-dev\"}[30s])",
     "legendFormat": "Revenue"
    }
   ]
  }
 ]
}